version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    command: start-dev
    environment:
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./custom-event-listener/target/custom-event-listener.jar:/opt/keycloak/providers/custom-event-listener.jar
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
